server:
  port: 8080

rsa:
  encrypt:
    open: true # 是否开启加密 true  or  false
    showLog: true # 是否打印加解密log true  or  false
    # RSA公钥 java生成
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCYXuc2xustPv5d1LrzpSYu0VjUab+Wc55KQSmXmueJWVbKQeGBHbGF9sr3CN8R8fw6HxUAgu5iZD+Nh2PEJ4Dl31FYzVSKTm7Z3Y92mLrvdigGAm9fxSCInnXcQkUS0TFLhrviGF3zSfmfk0oKlwI1S/grTNGEjWeG1NUBtRPXdwIDAQAB
    # RSA私钥 java生成
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJhe5zbG6y0+/l3UuvOlJi7RWNRpv5ZznkpBKZea54lZVspB4YEdsYX2yvcI3xHx/DofFQCC7mJkP42HY8QngOXfUVjNVIpObtndj3aYuu92KAYCb1/FIIieddxCRRLRMUuGu+IYXfNJ+Z+TSgqXAjVL+CtM0YSNZ4bU1QG1E9d3AgMBAAECgYBF7hhzvWumAmk/qyh6NeuGRTJdmoMBi+Kz9aAfIkrtcIEypnXWikg1UYTpR7sJQ2QdULKU34KEybmZPO/+0JqJL+d2IYbvG5Vf2REo1rzhK1mAYzaAPGIP2/AJZ9S8dwaeqVx2UsyJEIxzKQMwRFYe3FlBtP+g3CwGAMlpAbDLgQJBANRUA6dj7imItZWQkt/mNfqc1XPnbCJ0YBO3eygE60CydjQu6cv0aR6dfoCk1Sy9AP8ELfg62iPtxmbrKmhzJdcCQQC3td9LLQReMTt+/IqPOweufG74y115Jv1w9KKj0xKLNZJOLvDZVV6MehL3QNnFQHY9zVklqdWIDq3ikrAjb2dhAkEAsS6+sdO5LZ2wcfPoLMEt8Ekp8oN/AC1+81Uch6O7MQz7iMZRQWpewjaJFw71+VRrXWN+fPOXj33fH4lEpU7ZlwJAIAPM5w/wS+3ufWHLT8ysuQasXCUso/lcf3vSgBQ/jg0G8yMRC/7pnDeF6JrfmJV0Ra7skzi2oqBUQ0Dm+zXl4QJAGO3UdByaEP2ceIKPRrz4OSdkguGJPK5v6h0Bo/fcUuLPsyQadAOlAM+RTckbb4GjmbJC1CE6wuy2y1SWVb2lCw==